name: "Setup Nextflow"
description: "Install Nextflow and add it to the PATH"
author: "nf-core"
inputs:
  version:
    description: "The Nextflow version to download and use."
    required: false
    default: "latest-stable"
  all:
    description: "Whether to install every Nextflow release."
    required: false
    default: false
runs:
  using: "node20"
  main: "dist/index.js"
branding:
  icon: "shuffle"
  color: "green"
