name: "Setup Nextflow"
description: "Install Nextflow and add it to the PATH"
author: "nf-core"
inputs:
  version:
    description: "The Nextflow version to download and use."
    required: false
    default: "latest-stable"
  all:
    description: "Whether to install every Nextflow release."
    required: false
    default: false
  java-version:
    description: "The Java version to use."
    required: false
    default: "21"
  java-distribution:
    description: "The Java distribution to use."
    required: false
    default: "zulu"
runs:
  using: "composite"
  steps:
    - name: Setup Java
      uses: actions/setup-java@v2
      with:
        java-version: ${{ inputs.java-version }}
        distribution: ${{ inputs.java-distribution }}

    - uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Install npm
      shell: bash
      run: npm i -g npm@10

    - name: Install dependencies
      shell: bash
      run: npm ci

    - name: Install Nextflow
      shell: bash
      run: node lib/src/main.js
      with:
        version: ${{ inputs.version }}
        all: ${{ inputs.all }}

branding:
  icon: "shuffle"
  color: "green"
