name: "Setup Nextflow"
description: "Install Nextflow and add it to the PATH"
author: "nf-core"
inputs:
  version:
    description: "The Nextflow version to download (if necessary) and use. Example: 21.10.3"
    required: false
    default: "latest-stable"
  all:
    description: "Whether to install every Nextflow release via the '-all' distribution."
    required: false
    default: "false"
  java-version:
    description: "The Java version to install as the required dependency of Nextflow. Passed to the underlying setup-java action."
    required: false
    default: "17"
  java-distribution:
    description: "The Java distribution to install as the required dependency of Nextflow. Passed to the underlying setup-java action."
    required: false
    default: "zulu"
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
    - uses: actions/setup-node@v4
      with:
        node-version: "20"
        cache: "npm"
    - name: Install dependencies
      shell: bash
      run: npm ci
    - name: Build and Package
      shell: bash
      run: |
        npm run build
        npm run package
    - uses: actions/setup-java@8df1039502a15bceb9433410b1a100fbe190c53b
      with:
        java-version: ${{ inputs.java-version }}
        distribution: ${{ inputs.java-distribution }}
    - uses: ./subaction
      with:
        version: ${{ inputs.version }}
        all: ${{ inputs.all }}
branding:
  icon: "shuffle"
  color: "green"
