name: "Setup Nextflow"
description: "Install Nextflow and add it to the PATH"
author: "nf-core"
inputs:
  version:
    description: "The Nextflow version to download (if necessary) and use. Example: 21.10.3"
    required: false
    default: "latest-stable"
  all:
    description: "Whether to install every Nextflow release via the '-all' distribution."
    required: false
    default: "false"
  java-version:
    description: "The Java version to install as the required dependency of Nextflow. Passed to the underlying setup-java action."
    required: false
    default: "17"
  java-distribution:
    description: "The Java distribution to install as the required dependency of Nextflow. Passed to the underlying setup-java action."
    required: false
    default: "zulu"
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@cbb722410c2e876e24abbe8de2cc27693e501dcb
    - uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4
      with:
        node-version: "20"
        cache: "npm"
    - name: Install dependencies and build
      shell: bash
      run: |
        npm ci
        npm run package
    - uses: actions/setup-java@7136edc5e8145b3c0b6bae8f4e62706c74e76538
      with:
        java-version: ${{ inputs.java-version }}
        distribution: ${{ inputs.java-distribution }}
    - uses: ./subaction
      with:
        version: ${{ inputs.version }}
        all: ${{ inputs.all }}
branding:
  icon: "shuffle"
  color: "green"
