name: "Setup Nextflow"
description: "Install Nextflow and add it to the PATH"
author: "nf-core"
branding:
  icon: "shuffle"
  color: "green"
inputs:
  version:
    description: "The Nextflow version to download (if necessary) and use. Example: 21.10.3"
    required: false
    default: "latest-stable"
  java-version:
    description: "The Java version to install as the required dependency of Nextflow. Passed to the underlying setup-java action."
    required: false
    default: "17"
  java-distribution:
    description: "The Java distribution to install as the required dependency of Nextflow. Passed to the underlying setup-java action."
    required: false
    default: "zulu"
outputs:
  nextflow-version:
    description: "The version of Nextflow installed"
    value: ${{ steps.get_nextflow_version.outputs.version }}
runs:
  using: "composite"
  steps:

    - name: Install Java
      uses: actions/setup-java@8df1039502a15bceb9433410b1a100fbe190c53b # v4.5.0
      with:
        java-version: ${{ inputs.java-version }}
        distribution: ${{ inputs.java-distribution }}

    - name: Get Nextflow version
      id: get_nextflow_version
      run: ${{ github.action_path }}/get_nextflow_version.sh >> $GITHUB_OUTPUT
      shell: bash
      env:
        NXF_ACTION_VER: ${{ inputs.version }}

    - name: Cache installation
      uses: actions/cache@6849a6489940f00c2f30c0fb92c6274307ccb58a # v4.1.2
      with:
        key: nxf-${{ steps.get_nextflow_version.outputs.version }}
        path: |
          /usr/local/bin/nextflow
          ~/.nextflow

    - name: Install Nextflow
      env:
        NXF_VER: ${{ steps.get_nextflow_version.outputs.version }}
      run: |
        curl -s https://get.nextflow.io | bash
        sudo mv nextflow /usr/local/bin/

        # Run nextflow info to fetch assets
        nextflow info
      shell: bash
