name: Example builds

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  example-usage:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        nextflow_version:
          - "21.10.3"
          - "22.04"
          - "22.03.1-edge"
          - "latest"
          - "latest-stable"
          - "latest-edge"
          - "latest-everything"
        all_distribution:
          - true
          - false

    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      - uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4
        with:
          node-version: 20
          cache: "npm"
      - run: npm ci
      - run: npm run build
      - run: npm run package
      - uses: actions/setup-java@99b8673ff64fbf99d8d325f52d9a5bdedb8483e9 # v4
        if: ${{ env.ACT }}
        with:
          java-version: 11
          distribution: zulu
      - uses: ./
        with:
          version: ${{ matrix.nextflow_version }}
          all: ${{ matrix.all_distribution }}
      - run: nextflow -v

  example-maximized-build-space:
    runs-on: ubuntu-latest
    steps:
      - uses: easimon/maximize-build-space@fc881a613ad2a34aca9c9624518214ebc21dfc0c # v10
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      - uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4
        with:
          node-version: 20
          cache: "npm"
      - run: npm ci
      - run: npm run build
      - run: npm run package
      - uses: actions/setup-java@99b8673ff64fbf99d8d325f52d9a5bdedb8483e9 # v4
        if: ${{ env.ACT}}
        with:
          java-version: 11
          distribution: zulu
      - uses: ./
      - run: nextflow -v
