name: Example builds

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  example-usage:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        nextflow_version:
          - "21.10.3"
          - "22.03.1-edge"
          - "24.10.1"
          - "latest"
          - "latest-stable"
          - "latest-edge"
          - "latest-everything"

    steps:
      - name: Checkout repo
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Run action
        id: run-action
        uses: ./
        with:
          version: ${{ matrix.nextflow_version }}

      - name: Check Nextflow version
        run: nextflow -v

      - name: Print Nextflow version output
        run: echo ${{ steps.run-action.outputs.nextflow-version }}
