name: Run tests

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4
      - uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4
        with:
          node-version: 20
          cache: "npm"
      - run: npm ci
      - run: npm run build
      - run: npm run format:check
      - run: npm run lint
      - run: npm run package
      - run: npm run test
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: codecov/codecov-action@84508663e988701840491b86de86b666e8a86bed # v4
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
